### ISSUE TITLE
通过 @apply 的方式使用时, 引入的样式是错误的

### ISSUE THREAD

**Issue by Zhang-Wei-666** [action-hong/unocss-preset-scrollbar#1]
![Snipaste_2022-04-28_10-57-40](https://user-images.githubusercontent.com/37876877/165667719-90bee386-4367-4754-a6fd-85089e20f57d.png)

**Comment by action-hong** [comment]
unocss 还不支持在 @apply  使用 full-controller-rule

https://github.com/unocss/unocss/issues/717

**Comment by Zhang-Wei-666** [comment]
@action-hong 搞定, 你看看可以不

**Comment by action-hong** [comment]
@Zhang-Wei-666 感谢，`0.2.0`已发布
